// <auto-generated />
using System;
using DDDApi.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDApi.Infra.Data.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20220728003413_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DDDApi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("InData")
                        .HasColumnType("datetime")
                        .HasColumnName("InData");

                    b.Property<DateTime?>("MoData")
                        .HasColumnType("datetime")
                        .HasColumnName("MoData");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Password");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Email", "Password");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
