// <auto-generated />
using System;
using DDDApi.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDApi.Infra.Data.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DDDApi.Domain.Core.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("InData")
                        .HasColumnType("datetime")
                        .HasColumnName("InData");

                    b.Property<DateTime?>("MoData")
                        .HasColumnType("datetime")
                        .HasColumnName("MoData");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UserId");

                    b.HasIndex("Code", "UserId")
                        .IsUnique();

                    b.ToTable("Todo", (string)null);
                });

            modelBuilder.Entity("DDDApi.Domain.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("InData")
                        .HasColumnType("datetime")
                        .HasColumnName("InData");

                    b.Property<DateTime?>("MoData")
                        .HasColumnType("datetime")
                        .HasColumnName("MoData");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Password");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Email", "Password");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DDDApi.Domain.Core.Entities.Todo", b =>
                {
                    b.HasOne("DDDApi.Domain.Core.Entities.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TODO_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DDDApi.Domain.Core.Entities.User", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
